Algoritmo "50 primeiros pares"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/29/2022
Var
numero, count, somador: inteiro

Inicio
somador <- 2

enquanto count < 50 faca
         numero <- numero + somador
         somador  <- somador + 2
         
         //escreval(numero)
         count <- count + 1
fimenquanto

escreval("A soma é: ", numero)


Fimalgoritmo